version: '3.8'

services:
  chroma-db:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ../data/chromadb:/data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - PERSIST_DIRECTORY=/data
      - CHROMA_SERVER_AUTH_CREDENTIALS=your-secret-api-key
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=header
      - CHROMA_SERVER_AUTH_PROVIDER=token
    networks:
      - rag-network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ../logs:/app/logs
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - CHROMA_HOST=chroma-db
      - CHROMA_PORT=8000
      - CHROMA_AUTH_TOKEN=your-secret-api-key
      - EMBEDDING_MODEL=all-MiniLM-L6-v2  # BAAI/bge-base-en-v1.5      
    depends_on:
      - chroma-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_HOST=backend
      - API_PORT=8001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge 